### ISSUE TITLE
Programming language emoji  characters

### ISSUE THREAD

**Issue by passenger3e** [janlelis/character.construction#18]
First of all thank you for sharings.
I was searching emoji for java like icon to add it to my markdown file but couldn't find.(best i got is cofffe ☕ :) )
I don't know is it possible to make a custom emoji. you could add some emoji characters(and may be pictographs ) related to programming languages and actually interested in these on https://character.construction/ so I can copy desired emoji from there.

**Comment by janlelis** [comment]
You can propose a custom emoji here: https://www.unicode.org/emoji/proposals.html
