### ISSUE TITLE
Save for offline usage

### ISSUE THREAD

**Issue by p1r473** [janlelis/character.construction#9]
Hi,
Is there a way to save this for offline usage?
I tried saving as an HTML but the click-to-copy-paste doesnt seem to work
I downloaded the fork but not sure how to use .html.md.erb pages

**Comment by almereyda** [comment]
Did you try your browser's "Save as ..." feature? In Firefox I was able to store an offline copy of the "All Emojis" page that still brings the clipboard interaction.

You can also create a local copy of the site either with `httrack https://character.construction` or through `wget --mirror --random-wait --wait=2 -o character.construction.log --recursive --convert-links --page-requisites https://character.construction` which can then be served by a local webserver, or be opened directly in the web browser.

**Comment by p1r473** [comment]
Thanks that worked!
